import { ToastContainer } from 'react-toastify'
import '../globals.css'
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Register',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}
